# ──────────────────────────────────────────────────────────────────────────────
# config.properties  —  News Reader configuration
# ──────────────────────────────────────────────────────────────────────────────

# ── News API Configuration ────────────────────────────────────────────────────
news_api_token = <colocar um token valido>

# ── Filter properties ──────────────────────────────────────────────────────────
num_dias_recuo = 3
